# Generated by Django 4.2.6 on 2023-12-02 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.CharField(max_length=3)),
                ('title', models.CharField(max_length=50)),
                ('book_price', models.CharField(max_length=50)),
                ('rating', models.CharField(max_length=10)),
                ('author', models.CharField(max_length=50)),
                ('yop', models.CharField(max_length=50)),
                ('url', models.CharField(max_length=100)),
                ('genre', models.CharField(max_length=100)),
            ],
        ),
    ]
