# Generated by Django 4.2.6 on 2023-12-03 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=20)),
                ('content', models.TextField(max_length=1000)),
            ],
            options={
                'db_table': 'blog',
            },
        ),
        migrations.CreateModel(
            name='book_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=50)),
                ('rating', models.CharField(max_length=10)),
                ('author', models.CharField(max_length=50)),
                ('yop', models.CharField(max_length=50)),
                ('url', models.CharField(max_length=100)),
                ('genre', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'book_details',
            },
        ),
        migrations.DeleteModel(
            name='Record',
        ),
    ]
