# Generated by Django 4.2.6 on 2023-12-03 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myweb1', '0002_blog_book_details_delete_record'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='blog',
            table=None,
        ),
    ]
