# Generated by Django 4.2.6 on 2023-12-03 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myweb1', '0003_alter_blog_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='blog',
            table='blog',
        ),
    ]
