# Generated by Django 4.2.6 on 2023-12-03 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb1', '0004_alter_blog_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='blogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=20)),
                ('content', models.TextField(max_length=1000)),
            ],
            options={
                'db_table': 'blog',
            },
        ),
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=20)),
                ('subject', models.CharField(max_length=50)),
                ('notes', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='blog',
        ),
    ]
