# Generated by Django 4.2.6 on 2023-12-03 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myweb1', '0005_blogs_contact_delete_blog'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='contact',
            table='contact',
        ),
    ]
