# Generated by Django 4.2.6 on 2023-12-03 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myweb1', '0010_alter_contact_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='contact',
            table=None,
        ),
    ]
